version: '3'
services:
  service1:
    build: ./services/service_1
    container_name: service1
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - app-network
  
  service2:
    build: ./services/service_2
    container_name: service2
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge